// Generated by scripts/generate-api-types.mjs. Do not edit by hand.
export type ApiSchemas = {
  "AIModelLastTestRecord": {
  "tested_at"?: string | null;
  "text_model_status"?: string | null;
  "vision_model_status"?: string | null;
  "ok"?: boolean | null;
  "error_code"?: string | null;
  "error_message"?: string | null;
};
  "AIModelSettingsPatchRequest": {
  "provider"?: string | null;
  "base_url"?: string | null;
  "text_model"?: string | null;
  "vision_model"?: string | null;
  "endpoint"?: "chat_completions" | "responses" | null;
  "api_key"?: string | null;
};
  "AIModelSettingsResponse": {
  "provider": string;
  "provider_label": string;
  "base_url": string;
  "text_model": string;
  "vision_model": string;
  "endpoint": "chat_completions" | "responses";
  "key_status": "configured" | "missing";
  "key_source": "environment" | "encrypted_local" | "none";
  "storage_status": "windows_dpapi" | "unavailable";
  "last_test"?: AIModelLastTestRecord | null;
  "updated_at"?: string | null;
};
  "AIModelTestResponse": {
  "tested_at": string;
  "provider": string;
  "base_url": string;
  "text_model": string;
  "vision_model": string;
  "endpoint": "chat_completions" | "responses";
  "text_model_status": string;
  "vision_model_status": string;
  "ok": boolean;
  "error_code"?: string | null;
  "error_message"?: string | null;
};
  "AuthStatusResponse": {
  "auth_enabled": boolean;
  "disabled_reason": string;
  "local_user": Record<string, unknown>;
};
  "ChunkRecord": {
  "id": string;
  "source_id": string;
  "project_id": string;
  "content": string;
  "chunk_index": number;
  "citation_label": string;
  "metadata": Record<string, unknown>;
  "created_at": string;
};
  "CitationAnnotationBatchRequest": {
  "evidence_item_ids": string[];
  "annotation_type": "note" | "question" | "risk" | "follow_up";
  "content": string;
};
  "CitationAnnotationBatchResponse": {
  "evidence_pack_id": string;
  "requested_item_ids": string[];
  "created_count": number;
  "annotations": CitationAnnotationRecord[];
};
  "CitationAnnotationListResponse": {
  "evidence_pack_id": string;
  "annotations": CitationAnnotationRecord[];
  "counts_by_type": Record<string, unknown>;
  "total": number;
};
  "CitationAnnotationPatchRequest": {
  "annotation_type"?: "note" | "question" | "risk" | "follow_up" | null;
  "content"?: string | null;
};
  "CitationAnnotationRecord": {
  "id": string;
  "evidence_pack_id": string;
  "evidence_item_id": string;
  "annotation_type": "note" | "question" | "risk" | "follow_up";
  "content": string;
  "metadata": Record<string, unknown>;
  "created_at": string;
  "updated_at": string;
};
  "CitationAnnotationRequest": {
  "evidence_item_id": string;
  "annotation_type": "note" | "question" | "risk" | "follow_up";
  "content": string;
};
  "CitationCompareItem": {
  "id": string;
  "citation_label": string;
  "rank_score": number;
  "knowledge_unit_id": string | null;
  "knowledge_unit_title": string | null;
  "knowledge_unit_status": string | null;
  "knowledge_unit_type": string | null;
  "chunk_id": string | null;
  "chunk_citation_label": string | null;
  "source_id": string | null;
  "source_title": string | null;
  "source_origin": string | null;
  "source_type": string | null;
  "trace_path": Record<string, unknown>[];
  "copy_payload": Record<string, unknown>;
};
  "CitationCompareRequest": {
  "evidence_item_ids": string[];
};
  "CitationCompareResponse": {
  "evidence_pack_id": string;
  "item_count": number;
  "items": CitationCompareItem[];
  "differences": Record<string, unknown>;
  "copy_safe_summary": string;
};
  "Demo1CandidateKnowledgeUnitRecord": {
  "ku_id": string;
  "source_id": string;
  "chunk_id": string;
  "title": string;
  "summary": string;
  "keywords": string[];
  "tags": string[];
  "status": string;
  "confidence": number;
  "quality_note": string;
  "content_type": "very_short_text" | "short_note" | "paragraph_note" | "long_chunk";
};
  "Demo1ChunkRecord": {
  "chunk_id": string;
  "source_id": string;
  "chunk_index": number;
  "content": string;
  "char_count": number;
  "chunk_type": "very_short_chunk" | "short_chunk" | "normal_chunk" | "long_chunk";
  "start_offset": number;
  "end_offset": number;
  "chunk_basis": "semantic_clean_text" | "rule_clean_text";
};
  "Demo1CleaningRecord": {
  "content": string;
  "status": string;
  "before_char_count": number;
  "after_char_count": number;
  "note": string;
};
  "Demo1IngestionCommitRequest": {
  "preview_result"?: Demo1IngestionResult | null;
  "file_name"?: string | null;
  "input_type"?: "text" | "file";
  "raw_text"?: string | null;
  "file_content_base64"?: string | null;
  "content_type"?: string | null;
  "project_id"?: string;
};
  "Demo1IngestionRequest": {
  "file_name": string;
  "input_type"?: "text" | "file";
  "raw_text"?: string | null;
  "file_content_base64"?: string | null;
  "content_type"?: string | null;
  "project_id"?: string;
};
  "Demo1IngestionResult": {
  "received_file": Demo1ReceivedFileRecord;
  "source": Demo1SourceRecord;
  "metadata": Demo1MetadataRecord;
  "parsed": Demo1ParsedTextRecord;
  "semantic_parsing": Demo1SemanticParsingRecord;
  "rule_cleaning": Demo1RuleCleaningRecord;
  "semantic_cleaning": Demo1SemanticCleaningRecord;
  "cleaning": Demo1CleaningRecord;
  "chunk_basis": "semantic_clean_text" | "rule_clean_text";
  "chunks": Demo1ChunkRecord[];
  "candidate_knowledge_units": Demo1CandidateKnowledgeUnitRecord[];
  "candidate_ku_message": string;
  "pipeline_statuses": Demo1PipelineStatusRecord[];
  "model_error_code"?: string | null;
  "model_error_message"?: string | null;
  "persisted"?: boolean;
  "job_id"?: string | null;
  "review_task_ids"?: string[];
};
  "Demo1MetadataRecord": {
  "raw_length": number;
  "cleaned_length": number;
  "chunk_count": number;
  "candidate_ku_count": number;
  "model_provider": string;
  "model_name": string | null;
  "model_status": "available" | "unconfigured" | "error" | "invalid_response";
  "commit_status": "preview_only" | "committed";
  "parser_profile": string;
  "file_size_bytes"?: number | null;
  "parser_kind"?: "text_input" | "text_file" | "html_text" | "pdf_text" | "pdf_ocr" | "pdf_mixed" | "image_ocr";
  "parser_status"?: string;
  "parser_warnings"?: string[];
  "page_count"?: number | null;
  "image_count"?: number | null;
  "ocr_model_name"?: string | null;
  "parsed_page_count"?: number | null;
  "ocr_page_count"?: number | null;
  "skipped_page_count"?: number | null;
};
  "Demo1ParsedTextRecord": {
  "content": string;
  "status": string;
  "note": string;
};
  "Demo1PipelineStatusRecord": {
  "key": string;
  "label": string;
  "state": "done" | "loading" | "empty" | "error";
};
  "Demo1ReceivedFileRecord": {
  "file_name": string;
  "input_type": "text" | "file";
  "received_at": string;
  "raw_text_length": number;
  "process_status": string;
  "file_size_bytes"?: number | null;
};
  "Demo1RuleCleaningRecord": {
  "content": string;
  "status": string;
  "before_char_count": number;
  "after_char_count": number;
  "note": string;
  "operations"?: string[];
};
  "Demo1SemanticCleaningRecord": {
  "content": string;
  "status": string;
  "before_char_count": number;
  "after_char_count": number;
  "note": string;
  "cleaning_report": string;
  "noise_findings"?: string[];
  "quality_score": number;
  "fallback_reason"?: string | null;
};
  "Demo1SemanticParsingRecord": {
  "status": string;
  "summary": string;
  "titles"?: string[];
  "paragraph_notes"?: string[];
  "possible_toc"?: string[];
  "citations"?: string[];
  "noise_blocks"?: string[];
};
  "Demo1SourceRecord": {
  "source_id": string;
  "file_name": string;
  "input_type": "text" | "file";
  "created_at": string;
  "status": string;
  "raw_text_length": number;
  "clean_text_length": number;
  "chunk_count": number;
  "candidate_ku_count": number;
};
  "DiagnosticsResponse": {
  "created_at": string;
  "redacted": boolean;
  "includes_source_text": boolean;
  "summary": Record<string, unknown>;
};
  "EmbeddingRecord": {
  "id": string;
  "owner_type": string;
  "owner_id": string;
  "embedding_profile": string;
  "dimension": number;
  "status": string;
  "created_at": string;
};
  "EvidenceItemRecord": {
  "id": string;
  "evidence_pack_id": string;
  "knowledge_unit_id": string | null;
  "chunk_id": string | null;
  "source_id": string | null;
  "citation_label": string;
  "excerpt": string;
  "rank_score": number;
  "knowledge_unit_title"?: string | null;
  "knowledge_unit_status"?: string | null;
  "knowledge_unit_type"?: string | null;
  "chunk_citation_label"?: string | null;
  "chunk_content"?: string;
  "chunk_content_excerpt"?: string;
  "source_title"?: string | null;
  "source_origin"?: string | null;
  "source_type"?: string | null;
  "citation_trace"?: Record<string, unknown>;
  "created_at": string;
};
  "EvidenceOnlyRequest": {
  "query": string;
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
};
  "EvidenceOnlyResponse": {
  "retrieval_log_id": string;
  "evidence_pack_id": string;
  "answer_id": string;
  "output_type": string;
  "answer": string;
  "evidence_item_ids": string[];
  "citation_labels": string[];
  "citation_trace_summary": string;
  "provider_status": string;
  "fallback_reason": string | null;
};
  "EvidencePackDetail": {
  "id": string;
  "retrieval_log_id": string;
  "query": string;
  "query_explanation": Record<string, unknown>;
  "provider_status": string;
  "fallback_reason": string | null;
  "citation_trace_summary": string;
  "status": string;
  "failure_type": string | null;
  "summary": string;
  "detail_summary": EvidencePackDetailSummary;
  "items": EvidenceItemRecord[];
  "created_at": string;
};
  "EvidencePackDetailSummary": {
  "item_count": number;
  "source_count": number;
  "knowledge_unit_count": number;
  "citation_labels": string[];
  "rank_score_min": number | null;
  "rank_score_max": number | null;
  "focused_item_id": string | null;
  "no_evidence_reason": string | null;
  "annotation_count"?: number;
  "annotation_counts"?: Record<string, unknown>;
};
  "FeedbackDiagnosticsExportResponse": {
  "filename": string;
  "mime_type": string;
  "format": "json" | "csv";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "summary": FeedbackDiagnosticsSummary;
  "content": string;
  "redacted": boolean;
  "includes_source_text": boolean;
};
  "FeedbackDiagnosticsSummary": {
  "total": number;
  "by_type": Record<string, unknown>;
  "by_target_type": Record<string, unknown>;
  "positive_count": number;
  "negative_count": number;
  "last_event_at": string | null;
  "feedback_policy": Record<string, unknown>;
};
  "FeedbackEventRecord": {
  "id": string;
  "feedback_type": "click" | "useful" | "not_useful" | "favorite" | "bad_citation" | "missing_source" | "downrank_source";
  "target_type": string;
  "target_id": string;
  "evidence_pack_id": string | null;
  "ai_answer_id": string | null;
  "evidence_item_id": string | null;
  "comment": string | null;
  "ranking_effect": string;
  "query": string | null;
  "citation_label": string | null;
  "created_at": string;
};
  "FeedbackExportHistoryRecord": {
  "id": string;
  "filename": string;
  "format": "json" | "csv";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "summary": FeedbackDiagnosticsSummary;
  "content_sha256": string;
  "redacted": boolean;
  "includes_source_text": boolean;
};
  "FeedbackRequest": {
  "feedback_type": "click" | "useful" | "not_useful" | "favorite" | "bad_citation" | "missing_source" | "downrank_source";
  "evidence_pack_id"?: string | null;
  "ai_answer_id"?: string | null;
  "evidence_item_id"?: string | null;
  "comment"?: string | null;
};
  "FeedbackResponse": {
  "id": string;
  "feedback_type": "click" | "useful" | "not_useful" | "favorite" | "bad_citation" | "missing_source" | "downrank_source";
  "target_type": string;
  "target_id": string;
  "evidence_pack_id": string | null;
  "ai_answer_id": string | null;
  "evidence_item_id": string | null;
  "feedback_policy": Record<string, unknown>;
  "created_at": string;
};
  "FileInspectionSummary": {
  "id": string;
  "file_id": string;
  "job_id": string;
  "status": string;
  "extension": string;
  "mime_type": string | null;
  "size_bytes": number;
  "sha256": string;
  "header_summary": string;
  "risk_level": string;
  "risk_summary": string;
  "recoverable": boolean;
  "created_at": string;
  "updated_at": string;
};
  "FileIntegrityCheck": {
  "id": string;
  "upload_id": string;
  "file_id": string | null;
  "expected_sha256": string | null;
  "actual_sha256": string;
  "status": string;
  "message": string;
  "created_at": string;
};
  "FileRecord": {
  "id": string;
  "project_id": string;
  "original_filename": string;
  "content_type": string | null;
  "extension": string;
  "size_bytes": number;
  "sha256": string;
  "status": string;
  "inspection_status": string;
  "inspection": FileInspectionSummary | null;
  "created_at": string;
  "updated_at": string;
};
  "FolderCreateRequest": {
  "project_id"?: string;
  "parent_id"?: string | null;
  "name": string;
};
  "FolderRecord": {
  "id": string;
  "project_id": string;
  "parent_id": string | null;
  "name": string;
  "path": string;
  "mirror_tag_id": string | null;
  "created_at": string;
  "updated_at": string;
};
  "GraphPreviewEdge": {
  "id": string;
  "source_knowledge_unit_id": string;
  "target_knowledge_unit_id": string;
  "relation_type": "supports" | "contradicts" | "derived_from" | "example_of" | "part_of" | "depends_on" | "similar_to" | "used_for" | "updates" | "replaces";
  "status": string;
  "description": string | null;
  "source_title": string;
  "target_title": string;
  "created_at": string;
  "updated_at": string;
};
  "GraphPreviewNode": {
  "id": string;
  "title": string;
  "type": string;
  "status": string;
  "project_id": string;
  "primary_folder_id": string | null;
  "tags"?: TagRecord[];
};
  "GraphPreviewResponse": {
  "project_id": string;
  "filters": Record<string, unknown>;
  "summary": GraphPreviewSummary;
  "nodes": GraphPreviewNode[];
  "edges": GraphPreviewEdge[];
  "provider_status": string;
  "fallback_reason": string | null;
};
  "GraphPreviewSummary": {
  "project_id": string;
  "node_count": number;
  "edge_count": number;
  "relation_type_counts": Record<string, unknown>;
  "filters": Record<string, unknown>;
};
  "HTTPValidationError": {
  "detail"?: ValidationError[];
};
  "HealthResponse": {
  "ok": boolean;
  "app_name": string;
  "version": string;
  "request_id": string;
};
  "JobEvent": {
  "event_seq": number;
  "event_type": string;
  "message": string;
  "payload": Record<string, unknown>;
  "created_at": string;
};
  "JobSnapshot": {
  "id": string;
  "job_type": string;
  "status": string;
  "trace_id": string;
  "payload": Record<string, unknown>;
  "result": Record<string, unknown>;
  "events": JobEvent[];
};
  "KnowledgeExportHistoryRecord": {
  "id": string;
  "export_id": string;
  "export_kind": "knowledge_units" | "project";
  "filename": string;
  "format": "markdown" | "json" | "zip";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "summary": Record<string, unknown>;
  "content_sha256": string;
  "redacted": boolean;
  "includes_source_text": boolean;
};
  "KnowledgeExportResponse": {
  "export_id": string;
  "filename": string;
  "mime_type": string;
  "format": "markdown" | "json" | "zip";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "content"?: string | null;
  "content_base64"?: string | null;
  "redacted": boolean;
  "includes_source_text": boolean;
};
  "KnowledgeExtractRequest": {
  "source_id": string;
  "project_id"?: string;
  "force"?: boolean;
};
  "KnowledgeExtractResponse": {
  "job_id": string | null;
  "source_id": string;
  "candidate_knowledge_unit_ids": string[];
  "review_task_ids": string[];
  "embedding_ids": string[];
  "status": string;
  "reused": boolean;
  "fallback_reason": string | null;
};
  "KnowledgeRelationCreateRequest": {
  "project_id"?: string;
  "source_knowledge_unit_id": string;
  "target_knowledge_unit_id": string;
  "relation_type": "supports" | "contradicts" | "derived_from" | "example_of" | "part_of" | "depends_on" | "similar_to" | "used_for" | "updates" | "replaces";
  "description"?: string | null;
};
  "KnowledgeRelationDeleteResponse": {
  "id": string;
  "status": string;
  "updated_at": string;
};
  "KnowledgeRelationPatchRequest": {
  "relation_type"?: "supports" | "contradicts" | "derived_from" | "example_of" | "part_of" | "depends_on" | "similar_to" | "used_for" | "updates" | "replaces" | null;
  "description"?: string | null;
  "status"?: "confirmed" | "archived" | null;
};
  "KnowledgeRelationRecord": {
  "id": string;
  "project_id": string;
  "source_knowledge_unit_id": string;
  "target_knowledge_unit_id": string;
  "relation_type": "supports" | "contradicts" | "derived_from" | "example_of" | "part_of" | "depends_on" | "similar_to" | "used_for" | "updates" | "replaces";
  "status": string;
  "description": string | null;
  "source_title": string;
  "target_title": string;
  "created_by": string;
  "metadata": Record<string, unknown>;
  "created_at": string;
  "updated_at": string;
};
  "KnowledgeUnitDetail": {
  "id": string;
  "source_id": string;
  "chunk_id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "type": string;
  "content": string;
  "status": string;
  "user_verified": boolean;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "created_at": string;
  "updated_at": string;
  "source": SourceRecord | null;
  "chunk": ChunkRecord | null;
  "embeddings": EmbeddingRecord[];
  "review_task": Record<string, unknown> | null;
};
  "KnowledgeUnitExportRequest": {
  "format"?: "markdown" | "json";
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "knowledge_unit_ids"?: string[];
  "include_chunks"?: boolean;
  "include_sources"?: boolean;
  "include_pending_review"?: boolean;
};
  "KnowledgeUnitOrganizationBatchUpdateRequest": {
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "knowledge_unit_ids": string[];
};
  "KnowledgeUnitRecord": {
  "id": string;
  "source_id": string;
  "chunk_id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "type": string;
  "content": string;
  "status": string;
  "user_verified": boolean;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "created_at": string;
  "updated_at": string;
};
  "MemoryDraftRecord": {
  "id": string;
  "project_id": string;
  "source_answer_id": string;
  "content": string;
  "memory_type": "preference" | "decision" | "style" | "conclusion" | "reusable_context";
  "status": string;
  "permission": string;
  "user_confirmed": boolean;
  "review_task_id": string | null;
  "created_at": string;
  "updated_at": string;
};
  "MemoryDraftRequest": {
  "source_answer_id": string;
  "content": string;
  "memory_type": "preference" | "decision" | "style" | "conclusion" | "reusable_context";
  "permission"?: string;
  "project_id"?: string;
};
  "OrganizationBatchUpdateResponse": {
  "target_type": string;
  "project_id": string;
  "requested_ids": string[];
  "updated_ids": string[];
  "updated_count": number;
  "folder_id": string | null;
  "tags": TagRecord[];
  "synced_knowledge_unit_ids": string[];
  "updated_at": string;
};
  "OrganizationUpdateRequest": {
  "folder_id"?: string | null;
  "tag_ids"?: string[];
};
  "OrganizationUpdateResponse": {
  "target_type": string;
  "target_id": string;
  "project_id": string;
  "folder_id": string | null;
  "tags": TagRecord[];
  "synced_knowledge_unit_ids": string[];
  "updated_at": string;
};
  "ParseTaskRecord": {
  "id": string;
  "file_id": string;
  "source_id": string | null;
  "job_id": string;
  "parser_key": string;
  "status": string;
  "capability_status": string;
  "fallback_reason": string | null;
  "error_code": string | null;
  "source": SourceRecord | null;
  "chunk_ids": string[];
  "warnings": ParseWarningRecord[];
  "created_at": string;
  "updated_at": string;
};
  "ParseWarningRecord": {
  "id": string;
  "parse_task_id": string;
  "warning_type": string;
  "severity": string;
  "message": string;
  "source_location": string | null;
  "created_at": string;
};
  "ProjectCreateRequest": {
  "name": string;
  "description"?: string | null;
  "parent_id"?: string | null;
  "kb_type"?: "project_kb" | "reference_kb" | "person_kb" | "timeline_kb" | "inspiration_kb" | "method_kb" | "custom";
};
  "ProjectExportRequest": {
  "project_id"?: string;
  "include_pending_review"?: boolean;
  "format"?: string;
};
  "ProjectRecord": {
  "id": string;
  "user_id": string;
  "parent_id": string | null;
  "name": string;
  "description": string | null;
  "kb_type": string;
  "status": string;
  "metadata": Record<string, unknown>;
  "created_at": string;
  "updated_at": string;
};
  "RetrievalPreviewRequest": {
  "query": string;
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
};
  "RetrievalPreviewResponse": {
  "retrieval_log_id": string;
  "evidence_pack_id": string;
  "query": string;
  "query_explanation": Record<string, unknown>;
  "evidence_pack": EvidencePackDetail;
  "evidence_item_ids": string[];
  "citation_labels": string[];
  "citation_trace_summary": string;
  "provider_status": string;
  "fallback_reason": string | null;
};
  "ReviewActionResponse": {
  "review_task_id": string;
  "target_id": string;
  "status": string;
};
  "ReviewTask": {
  "id": string;
  "target_type": string;
  "target_id": string;
  "status": string;
  "payload": Record<string, unknown>;
};
  "RuntimeResponse": {
  "runtime_state": string;
  "status_reason": string | null;
  "sidecar": Record<string, unknown>;
  "database": Record<string, unknown>;
  "worker": Record<string, unknown>;
  "vector": Record<string, unknown>;
};
  "SettingsPatchRequest": {
  "language": "zh-CN" | "en-US";
};
  "SettingsResponse": {
  "language": "zh-CN" | "en-US";
  "persistence": string;
  "updated_at": string | null;
};
  "SourceDetail": {
  "id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "source_type": string;
  "source_origin": string;
  "content_hash": string;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "chunk_count": number;
  "created_at": string;
  "chunks": ChunkRecord[];
};
  "SourceOrganizationBatchUpdateRequest": {
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "source_ids": string[];
};
  "SourceRecord": {
  "id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "source_type": string;
  "source_origin": string;
  "content_hash": string;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "chunk_count": number;
  "created_at": string;
};
  "SystemStatusResponse": {
  "app": Record<string, unknown>;
  "database": Record<string, unknown>;
  "provider": Record<string, unknown>;
  "vector": Record<string, unknown>;
};
  "TagCreateRequest": {
  "project_id"?: string;
  "name": string;
  "namespace"?: "folder" | "topic" | "status" | "use" | "discipline" | "system" | "custom";
  "tag_type"?: "folder_tag" | "topic_tag" | "discipline_tag" | "status_tag" | "use_tag" | "system_tag" | "custom_tag";
  "description"?: string | null;
};
  "TagRecord": {
  "id": string;
  "project_id": string;
  "user_id": string;
  "name": string;
  "namespace": string;
  "tag_type": string;
  "description": string | null;
  "created_by": string;
  "created_at": string;
  "updated_at": string;
};
  "TextImportRequest": {
  "title": string;
  "content": string;
  "project_id"?: string;
};
  "TextImportResponse": {
  "job_id": string;
  "source_id": string;
  "chunk_ids": string[];
  "candidate_knowledge_unit_ids": string[];
  "review_task_ids": string[];
};
  "TextToSqlPreviewRequest": {
  "query": string;
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "limit"?: number;
};
  "TextToSqlPreviewResponse": {
  "retrieval_log_id": string;
  "template_id": string;
  "intent": string;
  "generated_sql": string;
  "parameters": Record<string, unknown>;
  "readonly": boolean;
  "safety_status": string;
  "columns": string[];
  "rows": Record<string, unknown>[];
  "row_count": number;
  "query_explanation": Record<string, unknown>;
  "provider_status": string;
  "fallback_reason": string | null;
};
  "UploadCreateRequest": {
  "filename": string;
  "size_bytes": number;
  "content_type"?: string | null;
  "sha256"?: string | null;
  "part_size"?: number | null;
  "project_id"?: string;
};
  "UploadPartResponse": {
  "upload_id": string;
  "part_no": number;
  "size_bytes": number;
  "sha256": string;
  "received_bytes": number;
  "status": string;
};
  "UploadPartSummary": {
  "part_no": number;
  "size_bytes": number;
  "sha256": string;
  "created_at": string;
};
  "UploadSnapshot": {
  "id": string;
  "project_id": string;
  "original_filename": string;
  "content_type": string | null;
  "expected_size": number;
  "part_size": number;
  "part_count": number;
  "expected_sha256": string | null;
  "received_bytes": number;
  "status": string;
  "file_id": string | null;
  "job_id": string | null;
  "recoverable": boolean;
  "error_code": string | null;
  "parts": UploadPartSummary[];
  "integrity_check": FileIntegrityCheck | null;
  "inspection": FileInspectionSummary | null;
  "created_at": string;
  "updated_at": string;
};
  "ValidationError": {
  "loc": string | number[];
  "msg": string;
  "type": string;
};
  "WorkspaceSummaryResponse": {
  "project_count": number;
  "folder_count": number;
  "tag_count": number;
  "upload_count": number;
  "file_count": number;
  "pending_file_count": number;
  "source_count": number;
  "chunk_count": number;
  "knowledge_unit_count": number;
  "pending_review_count": number;
  "evidence_pack_count": number;
};
};

export type AIModelLastTestRecord = {
  "tested_at"?: string | null;
  "text_model_status"?: string | null;
  "vision_model_status"?: string | null;
  "ok"?: boolean | null;
  "error_code"?: string | null;
  "error_message"?: string | null;
};

export type AIModelSettingsPatchRequest = {
  "provider"?: string | null;
  "base_url"?: string | null;
  "text_model"?: string | null;
  "vision_model"?: string | null;
  "endpoint"?: "chat_completions" | "responses" | null;
  "api_key"?: string | null;
};

export type AIModelSettingsResponse = {
  "provider": string;
  "provider_label": string;
  "base_url": string;
  "text_model": string;
  "vision_model": string;
  "endpoint": "chat_completions" | "responses";
  "key_status": "configured" | "missing";
  "key_source": "environment" | "encrypted_local" | "none";
  "storage_status": "windows_dpapi" | "unavailable";
  "last_test"?: AIModelLastTestRecord | null;
  "updated_at"?: string | null;
};

export type AIModelTestResponse = {
  "tested_at": string;
  "provider": string;
  "base_url": string;
  "text_model": string;
  "vision_model": string;
  "endpoint": "chat_completions" | "responses";
  "text_model_status": string;
  "vision_model_status": string;
  "ok": boolean;
  "error_code"?: string | null;
  "error_message"?: string | null;
};

export type AuthStatusResponse = {
  "auth_enabled": boolean;
  "disabled_reason": string;
  "local_user": Record<string, unknown>;
};

export type ChunkRecord = {
  "id": string;
  "source_id": string;
  "project_id": string;
  "content": string;
  "chunk_index": number;
  "citation_label": string;
  "metadata": Record<string, unknown>;
  "created_at": string;
};

export type CitationAnnotationBatchRequest = {
  "evidence_item_ids": string[];
  "annotation_type": "note" | "question" | "risk" | "follow_up";
  "content": string;
};

export type CitationAnnotationBatchResponse = {
  "evidence_pack_id": string;
  "requested_item_ids": string[];
  "created_count": number;
  "annotations": CitationAnnotationRecord[];
};

export type CitationAnnotationListResponse = {
  "evidence_pack_id": string;
  "annotations": CitationAnnotationRecord[];
  "counts_by_type": Record<string, unknown>;
  "total": number;
};

export type CitationAnnotationPatchRequest = {
  "annotation_type"?: "note" | "question" | "risk" | "follow_up" | null;
  "content"?: string | null;
};

export type CitationAnnotationRecord = {
  "id": string;
  "evidence_pack_id": string;
  "evidence_item_id": string;
  "annotation_type": "note" | "question" | "risk" | "follow_up";
  "content": string;
  "metadata": Record<string, unknown>;
  "created_at": string;
  "updated_at": string;
};

export type CitationAnnotationRequest = {
  "evidence_item_id": string;
  "annotation_type": "note" | "question" | "risk" | "follow_up";
  "content": string;
};

export type CitationCompareItem = {
  "id": string;
  "citation_label": string;
  "rank_score": number;
  "knowledge_unit_id": string | null;
  "knowledge_unit_title": string | null;
  "knowledge_unit_status": string | null;
  "knowledge_unit_type": string | null;
  "chunk_id": string | null;
  "chunk_citation_label": string | null;
  "source_id": string | null;
  "source_title": string | null;
  "source_origin": string | null;
  "source_type": string | null;
  "trace_path": Record<string, unknown>[];
  "copy_payload": Record<string, unknown>;
};

export type CitationCompareRequest = {
  "evidence_item_ids": string[];
};

export type CitationCompareResponse = {
  "evidence_pack_id": string;
  "item_count": number;
  "items": CitationCompareItem[];
  "differences": Record<string, unknown>;
  "copy_safe_summary": string;
};

export type Demo1CandidateKnowledgeUnitRecord = {
  "ku_id": string;
  "source_id": string;
  "chunk_id": string;
  "title": string;
  "summary": string;
  "keywords": string[];
  "tags": string[];
  "status": string;
  "confidence": number;
  "quality_note": string;
  "content_type": "very_short_text" | "short_note" | "paragraph_note" | "long_chunk";
};

export type Demo1ChunkRecord = {
  "chunk_id": string;
  "source_id": string;
  "chunk_index": number;
  "content": string;
  "char_count": number;
  "chunk_type": "very_short_chunk" | "short_chunk" | "normal_chunk" | "long_chunk";
  "start_offset": number;
  "end_offset": number;
  "chunk_basis": "semantic_clean_text" | "rule_clean_text";
};

export type Demo1CleaningRecord = {
  "content": string;
  "status": string;
  "before_char_count": number;
  "after_char_count": number;
  "note": string;
};

export type Demo1IngestionCommitRequest = {
  "preview_result"?: Demo1IngestionResult | null;
  "file_name"?: string | null;
  "input_type"?: "text" | "file";
  "raw_text"?: string | null;
  "file_content_base64"?: string | null;
  "content_type"?: string | null;
  "project_id"?: string;
};

export type Demo1IngestionRequest = {
  "file_name": string;
  "input_type"?: "text" | "file";
  "raw_text"?: string | null;
  "file_content_base64"?: string | null;
  "content_type"?: string | null;
  "project_id"?: string;
};

export type Demo1IngestionResult = {
  "received_file": Demo1ReceivedFileRecord;
  "source": Demo1SourceRecord;
  "metadata": Demo1MetadataRecord;
  "parsed": Demo1ParsedTextRecord;
  "semantic_parsing": Demo1SemanticParsingRecord;
  "rule_cleaning": Demo1RuleCleaningRecord;
  "semantic_cleaning": Demo1SemanticCleaningRecord;
  "cleaning": Demo1CleaningRecord;
  "chunk_basis": "semantic_clean_text" | "rule_clean_text";
  "chunks": Demo1ChunkRecord[];
  "candidate_knowledge_units": Demo1CandidateKnowledgeUnitRecord[];
  "candidate_ku_message": string;
  "pipeline_statuses": Demo1PipelineStatusRecord[];
  "model_error_code"?: string | null;
  "model_error_message"?: string | null;
  "persisted"?: boolean;
  "job_id"?: string | null;
  "review_task_ids"?: string[];
};

export type Demo1MetadataRecord = {
  "raw_length": number;
  "cleaned_length": number;
  "chunk_count": number;
  "candidate_ku_count": number;
  "model_provider": string;
  "model_name": string | null;
  "model_status": "available" | "unconfigured" | "error" | "invalid_response";
  "commit_status": "preview_only" | "committed";
  "parser_profile": string;
  "file_size_bytes"?: number | null;
  "parser_kind"?: "text_input" | "text_file" | "html_text" | "pdf_text" | "pdf_ocr" | "pdf_mixed" | "image_ocr";
  "parser_status"?: string;
  "parser_warnings"?: string[];
  "page_count"?: number | null;
  "image_count"?: number | null;
  "ocr_model_name"?: string | null;
  "parsed_page_count"?: number | null;
  "ocr_page_count"?: number | null;
  "skipped_page_count"?: number | null;
};

export type Demo1ParsedTextRecord = {
  "content": string;
  "status": string;
  "note": string;
};

export type Demo1PipelineStatusRecord = {
  "key": string;
  "label": string;
  "state": "done" | "loading" | "empty" | "error";
};

export type Demo1ReceivedFileRecord = {
  "file_name": string;
  "input_type": "text" | "file";
  "received_at": string;
  "raw_text_length": number;
  "process_status": string;
  "file_size_bytes"?: number | null;
};

export type Demo1RuleCleaningRecord = {
  "content": string;
  "status": string;
  "before_char_count": number;
  "after_char_count": number;
  "note": string;
  "operations"?: string[];
};

export type Demo1SemanticCleaningRecord = {
  "content": string;
  "status": string;
  "before_char_count": number;
  "after_char_count": number;
  "note": string;
  "cleaning_report": string;
  "noise_findings"?: string[];
  "quality_score": number;
  "fallback_reason"?: string | null;
};

export type Demo1SemanticParsingRecord = {
  "status": string;
  "summary": string;
  "titles"?: string[];
  "paragraph_notes"?: string[];
  "possible_toc"?: string[];
  "citations"?: string[];
  "noise_blocks"?: string[];
};

export type Demo1SourceRecord = {
  "source_id": string;
  "file_name": string;
  "input_type": "text" | "file";
  "created_at": string;
  "status": string;
  "raw_text_length": number;
  "clean_text_length": number;
  "chunk_count": number;
  "candidate_ku_count": number;
};

export type DiagnosticsResponse = {
  "created_at": string;
  "redacted": boolean;
  "includes_source_text": boolean;
  "summary": Record<string, unknown>;
};

export type EmbeddingRecord = {
  "id": string;
  "owner_type": string;
  "owner_id": string;
  "embedding_profile": string;
  "dimension": number;
  "status": string;
  "created_at": string;
};

export type EvidenceItemRecord = {
  "id": string;
  "evidence_pack_id": string;
  "knowledge_unit_id": string | null;
  "chunk_id": string | null;
  "source_id": string | null;
  "citation_label": string;
  "excerpt": string;
  "rank_score": number;
  "knowledge_unit_title"?: string | null;
  "knowledge_unit_status"?: string | null;
  "knowledge_unit_type"?: string | null;
  "chunk_citation_label"?: string | null;
  "chunk_content"?: string;
  "chunk_content_excerpt"?: string;
  "source_title"?: string | null;
  "source_origin"?: string | null;
  "source_type"?: string | null;
  "citation_trace"?: Record<string, unknown>;
  "created_at": string;
};

export type EvidenceOnlyRequest = {
  "query": string;
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
};

export type EvidenceOnlyResponse = {
  "retrieval_log_id": string;
  "evidence_pack_id": string;
  "answer_id": string;
  "output_type": string;
  "answer": string;
  "evidence_item_ids": string[];
  "citation_labels": string[];
  "citation_trace_summary": string;
  "provider_status": string;
  "fallback_reason": string | null;
};

export type EvidencePackDetail = {
  "id": string;
  "retrieval_log_id": string;
  "query": string;
  "query_explanation": Record<string, unknown>;
  "provider_status": string;
  "fallback_reason": string | null;
  "citation_trace_summary": string;
  "status": string;
  "failure_type": string | null;
  "summary": string;
  "detail_summary": EvidencePackDetailSummary;
  "items": EvidenceItemRecord[];
  "created_at": string;
};

export type EvidencePackDetailSummary = {
  "item_count": number;
  "source_count": number;
  "knowledge_unit_count": number;
  "citation_labels": string[];
  "rank_score_min": number | null;
  "rank_score_max": number | null;
  "focused_item_id": string | null;
  "no_evidence_reason": string | null;
  "annotation_count"?: number;
  "annotation_counts"?: Record<string, unknown>;
};

export type FeedbackDiagnosticsExportResponse = {
  "filename": string;
  "mime_type": string;
  "format": "json" | "csv";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "summary": FeedbackDiagnosticsSummary;
  "content": string;
  "redacted": boolean;
  "includes_source_text": boolean;
};

export type FeedbackDiagnosticsSummary = {
  "total": number;
  "by_type": Record<string, unknown>;
  "by_target_type": Record<string, unknown>;
  "positive_count": number;
  "negative_count": number;
  "last_event_at": string | null;
  "feedback_policy": Record<string, unknown>;
};

export type FeedbackEventRecord = {
  "id": string;
  "feedback_type": "click" | "useful" | "not_useful" | "favorite" | "bad_citation" | "missing_source" | "downrank_source";
  "target_type": string;
  "target_id": string;
  "evidence_pack_id": string | null;
  "ai_answer_id": string | null;
  "evidence_item_id": string | null;
  "comment": string | null;
  "ranking_effect": string;
  "query": string | null;
  "citation_label": string | null;
  "created_at": string;
};

export type FeedbackExportHistoryRecord = {
  "id": string;
  "filename": string;
  "format": "json" | "csv";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "summary": FeedbackDiagnosticsSummary;
  "content_sha256": string;
  "redacted": boolean;
  "includes_source_text": boolean;
};

export type FeedbackRequest = {
  "feedback_type": "click" | "useful" | "not_useful" | "favorite" | "bad_citation" | "missing_source" | "downrank_source";
  "evidence_pack_id"?: string | null;
  "ai_answer_id"?: string | null;
  "evidence_item_id"?: string | null;
  "comment"?: string | null;
};

export type FeedbackResponse = {
  "id": string;
  "feedback_type": "click" | "useful" | "not_useful" | "favorite" | "bad_citation" | "missing_source" | "downrank_source";
  "target_type": string;
  "target_id": string;
  "evidence_pack_id": string | null;
  "ai_answer_id": string | null;
  "evidence_item_id": string | null;
  "feedback_policy": Record<string, unknown>;
  "created_at": string;
};

export type FileInspectionSummary = {
  "id": string;
  "file_id": string;
  "job_id": string;
  "status": string;
  "extension": string;
  "mime_type": string | null;
  "size_bytes": number;
  "sha256": string;
  "header_summary": string;
  "risk_level": string;
  "risk_summary": string;
  "recoverable": boolean;
  "created_at": string;
  "updated_at": string;
};

export type FileIntegrityCheck = {
  "id": string;
  "upload_id": string;
  "file_id": string | null;
  "expected_sha256": string | null;
  "actual_sha256": string;
  "status": string;
  "message": string;
  "created_at": string;
};

export type FileRecord = {
  "id": string;
  "project_id": string;
  "original_filename": string;
  "content_type": string | null;
  "extension": string;
  "size_bytes": number;
  "sha256": string;
  "status": string;
  "inspection_status": string;
  "inspection": FileInspectionSummary | null;
  "created_at": string;
  "updated_at": string;
};

export type FolderCreateRequest = {
  "project_id"?: string;
  "parent_id"?: string | null;
  "name": string;
};

export type FolderRecord = {
  "id": string;
  "project_id": string;
  "parent_id": string | null;
  "name": string;
  "path": string;
  "mirror_tag_id": string | null;
  "created_at": string;
  "updated_at": string;
};

export type GraphPreviewEdge = {
  "id": string;
  "source_knowledge_unit_id": string;
  "target_knowledge_unit_id": string;
  "relation_type": "supports" | "contradicts" | "derived_from" | "example_of" | "part_of" | "depends_on" | "similar_to" | "used_for" | "updates" | "replaces";
  "status": string;
  "description": string | null;
  "source_title": string;
  "target_title": string;
  "created_at": string;
  "updated_at": string;
};

export type GraphPreviewNode = {
  "id": string;
  "title": string;
  "type": string;
  "status": string;
  "project_id": string;
  "primary_folder_id": string | null;
  "tags"?: TagRecord[];
};

export type GraphPreviewResponse = {
  "project_id": string;
  "filters": Record<string, unknown>;
  "summary": GraphPreviewSummary;
  "nodes": GraphPreviewNode[];
  "edges": GraphPreviewEdge[];
  "provider_status": string;
  "fallback_reason": string | null;
};

export type GraphPreviewSummary = {
  "project_id": string;
  "node_count": number;
  "edge_count": number;
  "relation_type_counts": Record<string, unknown>;
  "filters": Record<string, unknown>;
};

export type HTTPValidationError = {
  "detail"?: ValidationError[];
};

export type HealthResponse = {
  "ok": boolean;
  "app_name": string;
  "version": string;
  "request_id": string;
};

export type JobEvent = {
  "event_seq": number;
  "event_type": string;
  "message": string;
  "payload": Record<string, unknown>;
  "created_at": string;
};

export type JobSnapshot = {
  "id": string;
  "job_type": string;
  "status": string;
  "trace_id": string;
  "payload": Record<string, unknown>;
  "result": Record<string, unknown>;
  "events": JobEvent[];
};

export type KnowledgeExportHistoryRecord = {
  "id": string;
  "export_id": string;
  "export_kind": "knowledge_units" | "project";
  "filename": string;
  "format": "markdown" | "json" | "zip";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "summary": Record<string, unknown>;
  "content_sha256": string;
  "redacted": boolean;
  "includes_source_text": boolean;
};

export type KnowledgeExportResponse = {
  "export_id": string;
  "filename": string;
  "mime_type": string;
  "format": "markdown" | "json" | "zip";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "content"?: string | null;
  "content_base64"?: string | null;
  "redacted": boolean;
  "includes_source_text": boolean;
};

export type KnowledgeExtractRequest = {
  "source_id": string;
  "project_id"?: string;
  "force"?: boolean;
};

export type KnowledgeExtractResponse = {
  "job_id": string | null;
  "source_id": string;
  "candidate_knowledge_unit_ids": string[];
  "review_task_ids": string[];
  "embedding_ids": string[];
  "status": string;
  "reused": boolean;
  "fallback_reason": string | null;
};

export type KnowledgeRelationCreateRequest = {
  "project_id"?: string;
  "source_knowledge_unit_id": string;
  "target_knowledge_unit_id": string;
  "relation_type": "supports" | "contradicts" | "derived_from" | "example_of" | "part_of" | "depends_on" | "similar_to" | "used_for" | "updates" | "replaces";
  "description"?: string | null;
};

export type KnowledgeRelationDeleteResponse = {
  "id": string;
  "status": string;
  "updated_at": string;
};

export type KnowledgeRelationPatchRequest = {
  "relation_type"?: "supports" | "contradicts" | "derived_from" | "example_of" | "part_of" | "depends_on" | "similar_to" | "used_for" | "updates" | "replaces" | null;
  "description"?: string | null;
  "status"?: "confirmed" | "archived" | null;
};

export type KnowledgeRelationRecord = {
  "id": string;
  "project_id": string;
  "source_knowledge_unit_id": string;
  "target_knowledge_unit_id": string;
  "relation_type": "supports" | "contradicts" | "derived_from" | "example_of" | "part_of" | "depends_on" | "similar_to" | "used_for" | "updates" | "replaces";
  "status": string;
  "description": string | null;
  "source_title": string;
  "target_title": string;
  "created_by": string;
  "metadata": Record<string, unknown>;
  "created_at": string;
  "updated_at": string;
};

export type KnowledgeUnitDetail = {
  "id": string;
  "source_id": string;
  "chunk_id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "type": string;
  "content": string;
  "status": string;
  "user_verified": boolean;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "created_at": string;
  "updated_at": string;
  "source": SourceRecord | null;
  "chunk": ChunkRecord | null;
  "embeddings": EmbeddingRecord[];
  "review_task": Record<string, unknown> | null;
};

export type KnowledgeUnitExportRequest = {
  "format"?: "markdown" | "json";
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "knowledge_unit_ids"?: string[];
  "include_chunks"?: boolean;
  "include_sources"?: boolean;
  "include_pending_review"?: boolean;
};

export type KnowledgeUnitOrganizationBatchUpdateRequest = {
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "knowledge_unit_ids": string[];
};

export type KnowledgeUnitRecord = {
  "id": string;
  "source_id": string;
  "chunk_id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "type": string;
  "content": string;
  "status": string;
  "user_verified": boolean;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "created_at": string;
  "updated_at": string;
};

export type MemoryDraftRecord = {
  "id": string;
  "project_id": string;
  "source_answer_id": string;
  "content": string;
  "memory_type": "preference" | "decision" | "style" | "conclusion" | "reusable_context";
  "status": string;
  "permission": string;
  "user_confirmed": boolean;
  "review_task_id": string | null;
  "created_at": string;
  "updated_at": string;
};

export type MemoryDraftRequest = {
  "source_answer_id": string;
  "content": string;
  "memory_type": "preference" | "decision" | "style" | "conclusion" | "reusable_context";
  "permission"?: string;
  "project_id"?: string;
};

export type OrganizationBatchUpdateResponse = {
  "target_type": string;
  "project_id": string;
  "requested_ids": string[];
  "updated_ids": string[];
  "updated_count": number;
  "folder_id": string | null;
  "tags": TagRecord[];
  "synced_knowledge_unit_ids": string[];
  "updated_at": string;
};

export type OrganizationUpdateRequest = {
  "folder_id"?: string | null;
  "tag_ids"?: string[];
};

export type OrganizationUpdateResponse = {
  "target_type": string;
  "target_id": string;
  "project_id": string;
  "folder_id": string | null;
  "tags": TagRecord[];
  "synced_knowledge_unit_ids": string[];
  "updated_at": string;
};

export type ParseTaskRecord = {
  "id": string;
  "file_id": string;
  "source_id": string | null;
  "job_id": string;
  "parser_key": string;
  "status": string;
  "capability_status": string;
  "fallback_reason": string | null;
  "error_code": string | null;
  "source": SourceRecord | null;
  "chunk_ids": string[];
  "warnings": ParseWarningRecord[];
  "created_at": string;
  "updated_at": string;
};

export type ParseWarningRecord = {
  "id": string;
  "parse_task_id": string;
  "warning_type": string;
  "severity": string;
  "message": string;
  "source_location": string | null;
  "created_at": string;
};

export type ProjectCreateRequest = {
  "name": string;
  "description"?: string | null;
  "parent_id"?: string | null;
  "kb_type"?: "project_kb" | "reference_kb" | "person_kb" | "timeline_kb" | "inspiration_kb" | "method_kb" | "custom";
};

export type ProjectExportRequest = {
  "project_id"?: string;
  "include_pending_review"?: boolean;
  "format"?: string;
};

export type ProjectRecord = {
  "id": string;
  "user_id": string;
  "parent_id": string | null;
  "name": string;
  "description": string | null;
  "kb_type": string;
  "status": string;
  "metadata": Record<string, unknown>;
  "created_at": string;
  "updated_at": string;
};

export type RetrievalPreviewRequest = {
  "query": string;
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
};

export type RetrievalPreviewResponse = {
  "retrieval_log_id": string;
  "evidence_pack_id": string;
  "query": string;
  "query_explanation": Record<string, unknown>;
  "evidence_pack": EvidencePackDetail;
  "evidence_item_ids": string[];
  "citation_labels": string[];
  "citation_trace_summary": string;
  "provider_status": string;
  "fallback_reason": string | null;
};

export type ReviewActionResponse = {
  "review_task_id": string;
  "target_id": string;
  "status": string;
};

export type ReviewTask = {
  "id": string;
  "target_type": string;
  "target_id": string;
  "status": string;
  "payload": Record<string, unknown>;
};

export type RuntimeResponse = {
  "runtime_state": string;
  "status_reason": string | null;
  "sidecar": Record<string, unknown>;
  "database": Record<string, unknown>;
  "worker": Record<string, unknown>;
  "vector": Record<string, unknown>;
};

export type SettingsPatchRequest = {
  "language": "zh-CN" | "en-US";
};

export type SettingsResponse = {
  "language": "zh-CN" | "en-US";
  "persistence": string;
  "updated_at": string | null;
};

export type SourceDetail = {
  "id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "source_type": string;
  "source_origin": string;
  "content_hash": string;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "chunk_count": number;
  "created_at": string;
  "chunks": ChunkRecord[];
};

export type SourceOrganizationBatchUpdateRequest = {
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "source_ids": string[];
};

export type SourceRecord = {
  "id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "source_type": string;
  "source_origin": string;
  "content_hash": string;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "chunk_count": number;
  "created_at": string;
};

export type SystemStatusResponse = {
  "app": Record<string, unknown>;
  "database": Record<string, unknown>;
  "provider": Record<string, unknown>;
  "vector": Record<string, unknown>;
};

export type TagCreateRequest = {
  "project_id"?: string;
  "name": string;
  "namespace"?: "folder" | "topic" | "status" | "use" | "discipline" | "system" | "custom";
  "tag_type"?: "folder_tag" | "topic_tag" | "discipline_tag" | "status_tag" | "use_tag" | "system_tag" | "custom_tag";
  "description"?: string | null;
};

export type TagRecord = {
  "id": string;
  "project_id": string;
  "user_id": string;
  "name": string;
  "namespace": string;
  "tag_type": string;
  "description": string | null;
  "created_by": string;
  "created_at": string;
  "updated_at": string;
};

export type TextImportRequest = {
  "title": string;
  "content": string;
  "project_id"?: string;
};

export type TextImportResponse = {
  "job_id": string;
  "source_id": string;
  "chunk_ids": string[];
  "candidate_knowledge_unit_ids": string[];
  "review_task_ids": string[];
};

export type TextToSqlPreviewRequest = {
  "query": string;
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "limit"?: number;
};

export type TextToSqlPreviewResponse = {
  "retrieval_log_id": string;
  "template_id": string;
  "intent": string;
  "generated_sql": string;
  "parameters": Record<string, unknown>;
  "readonly": boolean;
  "safety_status": string;
  "columns": string[];
  "rows": Record<string, unknown>[];
  "row_count": number;
  "query_explanation": Record<string, unknown>;
  "provider_status": string;
  "fallback_reason": string | null;
};

export type UploadCreateRequest = {
  "filename": string;
  "size_bytes": number;
  "content_type"?: string | null;
  "sha256"?: string | null;
  "part_size"?: number | null;
  "project_id"?: string;
};

export type UploadPartResponse = {
  "upload_id": string;
  "part_no": number;
  "size_bytes": number;
  "sha256": string;
  "received_bytes": number;
  "status": string;
};

export type UploadPartSummary = {
  "part_no": number;
  "size_bytes": number;
  "sha256": string;
  "created_at": string;
};

export type UploadSnapshot = {
  "id": string;
  "project_id": string;
  "original_filename": string;
  "content_type": string | null;
  "expected_size": number;
  "part_size": number;
  "part_count": number;
  "expected_sha256": string | null;
  "received_bytes": number;
  "status": string;
  "file_id": string | null;
  "job_id": string | null;
  "recoverable": boolean;
  "error_code": string | null;
  "parts": UploadPartSummary[];
  "integrity_check": FileIntegrityCheck | null;
  "inspection": FileInspectionSummary | null;
  "created_at": string;
  "updated_at": string;
};

export type ValidationError = {
  "loc": string | number[];
  "msg": string;
  "type": string;
};

export type WorkspaceSummaryResponse = {
  "project_count": number;
  "folder_count": number;
  "tag_count": number;
  "upload_count": number;
  "file_count": number;
  "pending_file_count": number;
  "source_count": number;
  "chunk_count": number;
  "knowledge_unit_count": number;
  "pending_review_count": number;
  "evidence_pack_count": number;
};

export type ApiPath =
  | "/api/health"
  | "/api/system/runtime"
  | "/api/system/status"
  | "/api/system/diagnostics:export"
  | "/api/workspace/summary"
  | "/api/auth/status"
  | "/api/settings"
  | "/api/settings/ai-model"
  | "/api/settings/ai-model:test"
  | "/api/settings/ai-model/key"
  | "/api/projects"
  | "/api/folders"
  | "/api/tags"
  | "/api/sources/{source_id}/organization"
  | "/api/sources/organization:batch"
  | "/api/knowledge-units/{knowledge_unit_id}/organization"
  | "/api/knowledge-units/organization:batch"
  | "/api/uploads"
  | "/api/uploads/{upload_id}/parts/{part_no}"
  | "/api/uploads/{upload_id}:complete"
  | "/api/uploads/{upload_id}"
  | "/api/files"
  | "/api/files/{file_id}"
  | "/api/files/{file_id}:verify"
  | "/api/files/{file_id}:parse"
  | "/api/parse-tasks/{parse_task_id}"
  | "/api/sources"
  | "/api/sources/{source_id}"
  | "/api/knowledge-units:extract"
  | "/api/knowledge-units"
  | "/api/knowledge-units/{knowledge_unit_id}"
  | "/api/demo1/ingestion:preview"
  | "/api/demo1/ingestion:commit"
  | "/api/relations"
  | "/api/relations/{relation_id}"
  | "/api/graph/preview"
  | "/api/exports/knowledge-units"
  | "/api/exports/project"
  | "/api/exports/history"
  | "/api/exports/history/{history_id}"
  | "/api/feedback"
  | "/api/feedback/summary"
  | "/api/feedback/export"
  | "/api/feedback/export-history"
  | "/api/feedback/export-history/{history_id}"
  | "/api/memory-drafts"
  | "/api/memory-drafts/{memory_id}"
  | "/api/text-to-sql/preview"
  | "/api/text-imports"
  | "/api/jobs/{job_id}"
  | "/api/jobs/{job_id}/events:stream"
  | "/api/review-tasks"
  | "/api/review-tasks/{task_id}:confirm"
  | "/api/review-tasks/{task_id}:ignore"
  | "/api/retrieval/evidence-only"
  | "/api/retrieval/preview"
  | "/api/evidence-packs/{evidence_pack_id}"
  | "/api/evidence-packs/{evidence_pack_id}/annotations"
  | "/api/evidence-packs/{evidence_pack_id}/annotations:batch"
  | "/api/citation-annotations/{annotation_id}"
  | "/api/evidence-packs/{evidence_pack_id}/compare"
;
