// Generated by scripts/generate-api-types.mjs. Do not edit by hand.
export type ApiSchemas = {
  "AuthStatusResponse": {
  "auth_enabled": boolean;
  "disabled_reason": string;
  "local_user": Record<string, unknown>;
};
  "ChunkRecord": {
  "id": string;
  "source_id": string;
  "project_id": string;
  "content": string;
  "chunk_index": number;
  "citation_label": string;
  "metadata": Record<string, unknown>;
  "created_at": string;
};
  "CitationAnnotationBatchRequest": {
  "evidence_item_ids": string[];
  "annotation_type": "note" | "question" | "risk" | "follow_up";
  "content": string;
};
  "CitationAnnotationBatchResponse": {
  "evidence_pack_id": string;
  "requested_item_ids": string[];
  "created_count": number;
  "annotations": CitationAnnotationRecord[];
};
  "CitationAnnotationListResponse": {
  "evidence_pack_id": string;
  "annotations": CitationAnnotationRecord[];
  "counts_by_type": Record<string, unknown>;
  "total": number;
};
  "CitationAnnotationPatchRequest": {
  "annotation_type"?: "note" | "question" | "risk" | "follow_up" | null;
  "content"?: string | null;
};
  "CitationAnnotationRecord": {
  "id": string;
  "evidence_pack_id": string;
  "evidence_item_id": string;
  "annotation_type": "note" | "question" | "risk" | "follow_up";
  "content": string;
  "metadata": Record<string, unknown>;
  "created_at": string;
  "updated_at": string;
};
  "CitationAnnotationRequest": {
  "evidence_item_id": string;
  "annotation_type": "note" | "question" | "risk" | "follow_up";
  "content": string;
};
  "CitationCompareItem": {
  "id": string;
  "citation_label": string;
  "rank_score": number;
  "knowledge_unit_id": string | null;
  "knowledge_unit_title": string | null;
  "knowledge_unit_status": string | null;
  "knowledge_unit_type": string | null;
  "chunk_id": string | null;
  "chunk_citation_label": string | null;
  "source_id": string | null;
  "source_title": string | null;
  "source_origin": string | null;
  "source_type": string | null;
  "trace_path": Record<string, unknown>[];
  "copy_payload": Record<string, unknown>;
};
  "CitationCompareRequest": {
  "evidence_item_ids": string[];
};
  "CitationCompareResponse": {
  "evidence_pack_id": string;
  "item_count": number;
  "items": CitationCompareItem[];
  "differences": Record<string, unknown>;
  "copy_safe_summary": string;
};
  "DiagnosticsResponse": {
  "created_at": string;
  "redacted": boolean;
  "includes_source_text": boolean;
  "summary": Record<string, unknown>;
};
  "EmbeddingRecord": {
  "id": string;
  "owner_type": string;
  "owner_id": string;
  "embedding_profile": string;
  "dimension": number;
  "status": string;
  "created_at": string;
};
  "EvidenceItemRecord": {
  "id": string;
  "evidence_pack_id": string;
  "knowledge_unit_id": string | null;
  "chunk_id": string | null;
  "source_id": string | null;
  "citation_label": string;
  "excerpt": string;
  "rank_score": number;
  "knowledge_unit_title"?: string | null;
  "knowledge_unit_status"?: string | null;
  "knowledge_unit_type"?: string | null;
  "chunk_citation_label"?: string | null;
  "chunk_content_excerpt"?: string;
  "source_title"?: string | null;
  "source_origin"?: string | null;
  "source_type"?: string | null;
  "citation_trace"?: Record<string, unknown>;
  "created_at": string;
};
  "EvidenceOnlyRequest": {
  "query": string;
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
};
  "EvidenceOnlyResponse": {
  "retrieval_log_id": string;
  "evidence_pack_id": string;
  "answer_id": string;
  "output_type": string;
  "answer": string;
  "evidence_item_ids": string[];
  "citation_labels": string[];
  "citation_trace_summary": string;
  "provider_status": string;
  "fallback_reason": string | null;
};
  "EvidencePackDetail": {
  "id": string;
  "retrieval_log_id": string;
  "query": string;
  "query_explanation": Record<string, unknown>;
  "provider_status": string;
  "fallback_reason": string | null;
  "citation_trace_summary": string;
  "status": string;
  "failure_type": string | null;
  "summary": string;
  "detail_summary": EvidencePackDetailSummary;
  "items": EvidenceItemRecord[];
  "created_at": string;
};
  "EvidencePackDetailSummary": {
  "item_count": number;
  "source_count": number;
  "knowledge_unit_count": number;
  "citation_labels": string[];
  "rank_score_min": number | null;
  "rank_score_max": number | null;
  "focused_item_id": string | null;
  "no_evidence_reason": string | null;
  "annotation_count"?: number;
  "annotation_counts"?: Record<string, unknown>;
};
  "FeedbackDiagnosticsExportResponse": {
  "filename": string;
  "mime_type": string;
  "format": "json" | "csv";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "summary": FeedbackDiagnosticsSummary;
  "content": string;
  "redacted": boolean;
  "includes_source_text": boolean;
};
  "FeedbackDiagnosticsSummary": {
  "total": number;
  "by_type": Record<string, unknown>;
  "by_target_type": Record<string, unknown>;
  "positive_count": number;
  "negative_count": number;
  "last_event_at": string | null;
  "feedback_policy": Record<string, unknown>;
};
  "FeedbackEventRecord": {
  "id": string;
  "feedback_type": "click" | "useful" | "not_useful" | "favorite" | "bad_citation" | "missing_source" | "downrank_source";
  "target_type": string;
  "target_id": string;
  "evidence_pack_id": string | null;
  "ai_answer_id": string | null;
  "evidence_item_id": string | null;
  "comment": string | null;
  "ranking_effect": string;
  "query": string | null;
  "citation_label": string | null;
  "created_at": string;
};
  "FeedbackExportHistoryRecord": {
  "id": string;
  "filename": string;
  "format": "json" | "csv";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "summary": FeedbackDiagnosticsSummary;
  "content_sha256": string;
  "redacted": boolean;
  "includes_source_text": boolean;
};
  "FeedbackRequest": {
  "feedback_type": "click" | "useful" | "not_useful" | "favorite" | "bad_citation" | "missing_source" | "downrank_source";
  "evidence_pack_id"?: string | null;
  "ai_answer_id"?: string | null;
  "evidence_item_id"?: string | null;
  "comment"?: string | null;
};
  "FeedbackResponse": {
  "id": string;
  "feedback_type": "click" | "useful" | "not_useful" | "favorite" | "bad_citation" | "missing_source" | "downrank_source";
  "target_type": string;
  "target_id": string;
  "evidence_pack_id": string | null;
  "ai_answer_id": string | null;
  "evidence_item_id": string | null;
  "feedback_policy": Record<string, unknown>;
  "created_at": string;
};
  "FileInspectionSummary": {
  "id": string;
  "file_id": string;
  "job_id": string;
  "status": string;
  "extension": string;
  "mime_type": string | null;
  "size_bytes": number;
  "sha256": string;
  "header_summary": string;
  "risk_level": string;
  "risk_summary": string;
  "recoverable": boolean;
  "created_at": string;
  "updated_at": string;
};
  "FileIntegrityCheck": {
  "id": string;
  "upload_id": string;
  "file_id": string | null;
  "expected_sha256": string | null;
  "actual_sha256": string;
  "status": string;
  "message": string;
  "created_at": string;
};
  "FileRecord": {
  "id": string;
  "project_id": string;
  "original_filename": string;
  "content_type": string | null;
  "extension": string;
  "size_bytes": number;
  "sha256": string;
  "status": string;
  "inspection_status": string;
  "inspection": FileInspectionSummary | null;
  "created_at": string;
  "updated_at": string;
};
  "FolderCreateRequest": {
  "project_id"?: string;
  "parent_id"?: string | null;
  "name": string;
};
  "FolderRecord": {
  "id": string;
  "project_id": string;
  "parent_id": string | null;
  "name": string;
  "path": string;
  "mirror_tag_id": string | null;
  "created_at": string;
  "updated_at": string;
};
  "HTTPValidationError": {
  "detail"?: ValidationError[];
};
  "HealthResponse": {
  "ok": boolean;
  "app_name": string;
  "version": string;
  "request_id": string;
};
  "JobEvent": {
  "event_seq": number;
  "event_type": string;
  "message": string;
  "payload": Record<string, unknown>;
  "created_at": string;
};
  "JobSnapshot": {
  "id": string;
  "job_type": string;
  "status": string;
  "trace_id": string;
  "payload": Record<string, unknown>;
  "result": Record<string, unknown>;
  "events": JobEvent[];
};
  "KnowledgeExportHistoryRecord": {
  "id": string;
  "export_id": string;
  "export_kind": "knowledge_units" | "project";
  "filename": string;
  "format": "markdown" | "json" | "zip";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "summary": Record<string, unknown>;
  "content_sha256": string;
  "redacted": boolean;
  "includes_source_text": boolean;
};
  "KnowledgeExportResponse": {
  "export_id": string;
  "filename": string;
  "mime_type": string;
  "format": "markdown" | "json" | "zip";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "content"?: string | null;
  "content_base64"?: string | null;
  "redacted": boolean;
  "includes_source_text": boolean;
};
  "KnowledgeExtractRequest": {
  "source_id": string;
  "project_id"?: string;
  "force"?: boolean;
};
  "KnowledgeExtractResponse": {
  "job_id": string | null;
  "source_id": string;
  "candidate_knowledge_unit_ids": string[];
  "review_task_ids": string[];
  "embedding_ids": string[];
  "status": string;
  "reused": boolean;
  "fallback_reason": string | null;
};
  "KnowledgeUnitDetail": {
  "id": string;
  "source_id": string;
  "chunk_id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "type": string;
  "content": string;
  "status": string;
  "user_verified": boolean;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "created_at": string;
  "updated_at": string;
  "source": SourceRecord | null;
  "chunk": ChunkRecord | null;
  "embeddings": EmbeddingRecord[];
  "review_task": Record<string, unknown> | null;
};
  "KnowledgeUnitExportRequest": {
  "format"?: "markdown" | "json";
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "knowledge_unit_ids"?: string[];
  "include_chunks"?: boolean;
  "include_sources"?: boolean;
  "include_pending_review"?: boolean;
};
  "KnowledgeUnitOrganizationBatchUpdateRequest": {
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "knowledge_unit_ids": string[];
};
  "KnowledgeUnitRecord": {
  "id": string;
  "source_id": string;
  "chunk_id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "type": string;
  "content": string;
  "status": string;
  "user_verified": boolean;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "created_at": string;
  "updated_at": string;
};
  "MemoryDraftRecord": {
  "id": string;
  "project_id": string;
  "source_answer_id": string;
  "content": string;
  "memory_type": "preference" | "decision" | "style" | "conclusion" | "reusable_context";
  "status": string;
  "permission": string;
  "user_confirmed": boolean;
  "review_task_id": string | null;
  "created_at": string;
  "updated_at": string;
};
  "MemoryDraftRequest": {
  "source_answer_id": string;
  "content": string;
  "memory_type": "preference" | "decision" | "style" | "conclusion" | "reusable_context";
  "permission"?: string;
  "project_id"?: string;
};
  "OrganizationBatchUpdateResponse": {
  "target_type": string;
  "project_id": string;
  "requested_ids": string[];
  "updated_ids": string[];
  "updated_count": number;
  "folder_id": string | null;
  "tags": TagRecord[];
  "synced_knowledge_unit_ids": string[];
  "updated_at": string;
};
  "OrganizationUpdateRequest": {
  "folder_id"?: string | null;
  "tag_ids"?: string[];
};
  "OrganizationUpdateResponse": {
  "target_type": string;
  "target_id": string;
  "project_id": string;
  "folder_id": string | null;
  "tags": TagRecord[];
  "synced_knowledge_unit_ids": string[];
  "updated_at": string;
};
  "ParseTaskRecord": {
  "id": string;
  "file_id": string;
  "source_id": string | null;
  "job_id": string;
  "parser_key": string;
  "status": string;
  "capability_status": string;
  "fallback_reason": string | null;
  "error_code": string | null;
  "source": SourceRecord | null;
  "chunk_ids": string[];
  "warnings": ParseWarningRecord[];
  "created_at": string;
  "updated_at": string;
};
  "ParseWarningRecord": {
  "id": string;
  "parse_task_id": string;
  "warning_type": string;
  "severity": string;
  "message": string;
  "source_location": string | null;
  "created_at": string;
};
  "ProjectCreateRequest": {
  "name": string;
  "description"?: string | null;
  "parent_id"?: string | null;
  "kb_type"?: "project_kb" | "reference_kb" | "person_kb" | "timeline_kb" | "inspiration_kb" | "method_kb" | "custom";
};
  "ProjectExportRequest": {
  "project_id"?: string;
  "include_pending_review"?: boolean;
  "format"?: string;
};
  "ProjectRecord": {
  "id": string;
  "user_id": string;
  "parent_id": string | null;
  "name": string;
  "description": string | null;
  "kb_type": string;
  "status": string;
  "metadata": Record<string, unknown>;
  "created_at": string;
  "updated_at": string;
};
  "RetrievalPreviewRequest": {
  "query": string;
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
};
  "RetrievalPreviewResponse": {
  "retrieval_log_id": string;
  "evidence_pack_id": string;
  "query": string;
  "query_explanation": Record<string, unknown>;
  "evidence_pack": EvidencePackDetail;
  "evidence_item_ids": string[];
  "citation_labels": string[];
  "citation_trace_summary": string;
  "provider_status": string;
  "fallback_reason": string | null;
};
  "ReviewActionResponse": {
  "review_task_id": string;
  "target_id": string;
  "status": string;
};
  "ReviewTask": {
  "id": string;
  "target_type": string;
  "target_id": string;
  "status": string;
  "payload": Record<string, unknown>;
};
  "RuntimeResponse": {
  "runtime_state": string;
  "status_reason": string | null;
  "sidecar": Record<string, unknown>;
  "database": Record<string, unknown>;
  "worker": Record<string, unknown>;
  "vector": Record<string, unknown>;
};
  "SettingsPatchRequest": {
  "language": "zh-CN" | "en-US";
};
  "SettingsResponse": {
  "language": "zh-CN" | "en-US";
  "persistence": string;
  "updated_at": string | null;
};
  "SourceDetail": {
  "id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "source_type": string;
  "source_origin": string;
  "content_hash": string;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "chunk_count": number;
  "created_at": string;
  "chunks": ChunkRecord[];
};
  "SourceOrganizationBatchUpdateRequest": {
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "source_ids": string[];
};
  "SourceRecord": {
  "id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "source_type": string;
  "source_origin": string;
  "content_hash": string;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "chunk_count": number;
  "created_at": string;
};
  "SystemStatusResponse": {
  "app": Record<string, unknown>;
  "database": Record<string, unknown>;
  "provider": Record<string, unknown>;
  "vector": Record<string, unknown>;
};
  "TagCreateRequest": {
  "project_id"?: string;
  "name": string;
  "namespace"?: "folder" | "topic" | "status" | "use" | "discipline" | "system" | "custom";
  "tag_type"?: "folder_tag" | "topic_tag" | "discipline_tag" | "status_tag" | "use_tag" | "system_tag" | "custom_tag";
  "description"?: string | null;
};
  "TagRecord": {
  "id": string;
  "project_id": string;
  "user_id": string;
  "name": string;
  "namespace": string;
  "tag_type": string;
  "description": string | null;
  "created_by": string;
  "created_at": string;
  "updated_at": string;
};
  "TextImportRequest": {
  "title": string;
  "content": string;
  "project_id"?: string;
};
  "TextImportResponse": {
  "job_id": string;
  "source_id": string;
  "chunk_ids": string[];
  "candidate_knowledge_unit_ids": string[];
  "review_task_ids": string[];
};
  "TextToSqlPreviewRequest": {
  "query": string;
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "limit"?: number;
};
  "TextToSqlPreviewResponse": {
  "retrieval_log_id": string;
  "template_id": string;
  "intent": string;
  "generated_sql": string;
  "parameters": Record<string, unknown>;
  "readonly": boolean;
  "safety_status": string;
  "columns": string[];
  "rows": Record<string, unknown>[];
  "row_count": number;
  "query_explanation": Record<string, unknown>;
  "provider_status": string;
  "fallback_reason": string | null;
};
  "UploadCreateRequest": {
  "filename": string;
  "size_bytes": number;
  "content_type"?: string | null;
  "sha256"?: string | null;
  "part_size"?: number | null;
  "project_id"?: string;
};
  "UploadPartResponse": {
  "upload_id": string;
  "part_no": number;
  "size_bytes": number;
  "sha256": string;
  "received_bytes": number;
  "status": string;
};
  "UploadPartSummary": {
  "part_no": number;
  "size_bytes": number;
  "sha256": string;
  "created_at": string;
};
  "UploadSnapshot": {
  "id": string;
  "project_id": string;
  "original_filename": string;
  "content_type": string | null;
  "expected_size": number;
  "part_size": number;
  "part_count": number;
  "expected_sha256": string | null;
  "received_bytes": number;
  "status": string;
  "file_id": string | null;
  "job_id": string | null;
  "recoverable": boolean;
  "error_code": string | null;
  "parts": UploadPartSummary[];
  "integrity_check": FileIntegrityCheck | null;
  "inspection": FileInspectionSummary | null;
  "created_at": string;
  "updated_at": string;
};
  "ValidationError": {
  "loc": string | number[];
  "msg": string;
  "type": string;
};
  "WorkspaceSummaryResponse": {
  "project_count": number;
  "folder_count": number;
  "tag_count": number;
  "upload_count": number;
  "file_count": number;
  "pending_file_count": number;
  "source_count": number;
  "chunk_count": number;
  "knowledge_unit_count": number;
  "pending_review_count": number;
  "evidence_pack_count": number;
};
};

export type AuthStatusResponse = {
  "auth_enabled": boolean;
  "disabled_reason": string;
  "local_user": Record<string, unknown>;
};

export type ChunkRecord = {
  "id": string;
  "source_id": string;
  "project_id": string;
  "content": string;
  "chunk_index": number;
  "citation_label": string;
  "metadata": Record<string, unknown>;
  "created_at": string;
};

export type CitationAnnotationBatchRequest = {
  "evidence_item_ids": string[];
  "annotation_type": "note" | "question" | "risk" | "follow_up";
  "content": string;
};

export type CitationAnnotationBatchResponse = {
  "evidence_pack_id": string;
  "requested_item_ids": string[];
  "created_count": number;
  "annotations": CitationAnnotationRecord[];
};

export type CitationAnnotationListResponse = {
  "evidence_pack_id": string;
  "annotations": CitationAnnotationRecord[];
  "counts_by_type": Record<string, unknown>;
  "total": number;
};

export type CitationAnnotationPatchRequest = {
  "annotation_type"?: "note" | "question" | "risk" | "follow_up" | null;
  "content"?: string | null;
};

export type CitationAnnotationRecord = {
  "id": string;
  "evidence_pack_id": string;
  "evidence_item_id": string;
  "annotation_type": "note" | "question" | "risk" | "follow_up";
  "content": string;
  "metadata": Record<string, unknown>;
  "created_at": string;
  "updated_at": string;
};

export type CitationAnnotationRequest = {
  "evidence_item_id": string;
  "annotation_type": "note" | "question" | "risk" | "follow_up";
  "content": string;
};

export type CitationCompareItem = {
  "id": string;
  "citation_label": string;
  "rank_score": number;
  "knowledge_unit_id": string | null;
  "knowledge_unit_title": string | null;
  "knowledge_unit_status": string | null;
  "knowledge_unit_type": string | null;
  "chunk_id": string | null;
  "chunk_citation_label": string | null;
  "source_id": string | null;
  "source_title": string | null;
  "source_origin": string | null;
  "source_type": string | null;
  "trace_path": Record<string, unknown>[];
  "copy_payload": Record<string, unknown>;
};

export type CitationCompareRequest = {
  "evidence_item_ids": string[];
};

export type CitationCompareResponse = {
  "evidence_pack_id": string;
  "item_count": number;
  "items": CitationCompareItem[];
  "differences": Record<string, unknown>;
  "copy_safe_summary": string;
};

export type DiagnosticsResponse = {
  "created_at": string;
  "redacted": boolean;
  "includes_source_text": boolean;
  "summary": Record<string, unknown>;
};

export type EmbeddingRecord = {
  "id": string;
  "owner_type": string;
  "owner_id": string;
  "embedding_profile": string;
  "dimension": number;
  "status": string;
  "created_at": string;
};

export type EvidenceItemRecord = {
  "id": string;
  "evidence_pack_id": string;
  "knowledge_unit_id": string | null;
  "chunk_id": string | null;
  "source_id": string | null;
  "citation_label": string;
  "excerpt": string;
  "rank_score": number;
  "knowledge_unit_title"?: string | null;
  "knowledge_unit_status"?: string | null;
  "knowledge_unit_type"?: string | null;
  "chunk_citation_label"?: string | null;
  "chunk_content_excerpt"?: string;
  "source_title"?: string | null;
  "source_origin"?: string | null;
  "source_type"?: string | null;
  "citation_trace"?: Record<string, unknown>;
  "created_at": string;
};

export type EvidenceOnlyRequest = {
  "query": string;
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
};

export type EvidenceOnlyResponse = {
  "retrieval_log_id": string;
  "evidence_pack_id": string;
  "answer_id": string;
  "output_type": string;
  "answer": string;
  "evidence_item_ids": string[];
  "citation_labels": string[];
  "citation_trace_summary": string;
  "provider_status": string;
  "fallback_reason": string | null;
};

export type EvidencePackDetail = {
  "id": string;
  "retrieval_log_id": string;
  "query": string;
  "query_explanation": Record<string, unknown>;
  "provider_status": string;
  "fallback_reason": string | null;
  "citation_trace_summary": string;
  "status": string;
  "failure_type": string | null;
  "summary": string;
  "detail_summary": EvidencePackDetailSummary;
  "items": EvidenceItemRecord[];
  "created_at": string;
};

export type EvidencePackDetailSummary = {
  "item_count": number;
  "source_count": number;
  "knowledge_unit_count": number;
  "citation_labels": string[];
  "rank_score_min": number | null;
  "rank_score_max": number | null;
  "focused_item_id": string | null;
  "no_evidence_reason": string | null;
  "annotation_count"?: number;
  "annotation_counts"?: Record<string, unknown>;
};

export type FeedbackDiagnosticsExportResponse = {
  "filename": string;
  "mime_type": string;
  "format": "json" | "csv";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "summary": FeedbackDiagnosticsSummary;
  "content": string;
  "redacted": boolean;
  "includes_source_text": boolean;
};

export type FeedbackDiagnosticsSummary = {
  "total": number;
  "by_type": Record<string, unknown>;
  "by_target_type": Record<string, unknown>;
  "positive_count": number;
  "negative_count": number;
  "last_event_at": string | null;
  "feedback_policy": Record<string, unknown>;
};

export type FeedbackEventRecord = {
  "id": string;
  "feedback_type": "click" | "useful" | "not_useful" | "favorite" | "bad_citation" | "missing_source" | "downrank_source";
  "target_type": string;
  "target_id": string;
  "evidence_pack_id": string | null;
  "ai_answer_id": string | null;
  "evidence_item_id": string | null;
  "comment": string | null;
  "ranking_effect": string;
  "query": string | null;
  "citation_label": string | null;
  "created_at": string;
};

export type FeedbackExportHistoryRecord = {
  "id": string;
  "filename": string;
  "format": "json" | "csv";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "summary": FeedbackDiagnosticsSummary;
  "content_sha256": string;
  "redacted": boolean;
  "includes_source_text": boolean;
};

export type FeedbackRequest = {
  "feedback_type": "click" | "useful" | "not_useful" | "favorite" | "bad_citation" | "missing_source" | "downrank_source";
  "evidence_pack_id"?: string | null;
  "ai_answer_id"?: string | null;
  "evidence_item_id"?: string | null;
  "comment"?: string | null;
};

export type FeedbackResponse = {
  "id": string;
  "feedback_type": "click" | "useful" | "not_useful" | "favorite" | "bad_citation" | "missing_source" | "downrank_source";
  "target_type": string;
  "target_id": string;
  "evidence_pack_id": string | null;
  "ai_answer_id": string | null;
  "evidence_item_id": string | null;
  "feedback_policy": Record<string, unknown>;
  "created_at": string;
};

export type FileInspectionSummary = {
  "id": string;
  "file_id": string;
  "job_id": string;
  "status": string;
  "extension": string;
  "mime_type": string | null;
  "size_bytes": number;
  "sha256": string;
  "header_summary": string;
  "risk_level": string;
  "risk_summary": string;
  "recoverable": boolean;
  "created_at": string;
  "updated_at": string;
};

export type FileIntegrityCheck = {
  "id": string;
  "upload_id": string;
  "file_id": string | null;
  "expected_sha256": string | null;
  "actual_sha256": string;
  "status": string;
  "message": string;
  "created_at": string;
};

export type FileRecord = {
  "id": string;
  "project_id": string;
  "original_filename": string;
  "content_type": string | null;
  "extension": string;
  "size_bytes": number;
  "sha256": string;
  "status": string;
  "inspection_status": string;
  "inspection": FileInspectionSummary | null;
  "created_at": string;
  "updated_at": string;
};

export type FolderCreateRequest = {
  "project_id"?: string;
  "parent_id"?: string | null;
  "name": string;
};

export type FolderRecord = {
  "id": string;
  "project_id": string;
  "parent_id": string | null;
  "name": string;
  "path": string;
  "mirror_tag_id": string | null;
  "created_at": string;
  "updated_at": string;
};

export type HTTPValidationError = {
  "detail"?: ValidationError[];
};

export type HealthResponse = {
  "ok": boolean;
  "app_name": string;
  "version": string;
  "request_id": string;
};

export type JobEvent = {
  "event_seq": number;
  "event_type": string;
  "message": string;
  "payload": Record<string, unknown>;
  "created_at": string;
};

export type JobSnapshot = {
  "id": string;
  "job_type": string;
  "status": string;
  "trace_id": string;
  "payload": Record<string, unknown>;
  "result": Record<string, unknown>;
  "events": JobEvent[];
};

export type KnowledgeExportHistoryRecord = {
  "id": string;
  "export_id": string;
  "export_kind": "knowledge_units" | "project";
  "filename": string;
  "format": "markdown" | "json" | "zip";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "summary": Record<string, unknown>;
  "content_sha256": string;
  "redacted": boolean;
  "includes_source_text": boolean;
};

export type KnowledgeExportResponse = {
  "export_id": string;
  "filename": string;
  "mime_type": string;
  "format": "markdown" | "json" | "zip";
  "record_count": number;
  "generated_at": string;
  "filters": Record<string, unknown>;
  "content"?: string | null;
  "content_base64"?: string | null;
  "redacted": boolean;
  "includes_source_text": boolean;
};

export type KnowledgeExtractRequest = {
  "source_id": string;
  "project_id"?: string;
  "force"?: boolean;
};

export type KnowledgeExtractResponse = {
  "job_id": string | null;
  "source_id": string;
  "candidate_knowledge_unit_ids": string[];
  "review_task_ids": string[];
  "embedding_ids": string[];
  "status": string;
  "reused": boolean;
  "fallback_reason": string | null;
};

export type KnowledgeUnitDetail = {
  "id": string;
  "source_id": string;
  "chunk_id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "type": string;
  "content": string;
  "status": string;
  "user_verified": boolean;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "created_at": string;
  "updated_at": string;
  "source": SourceRecord | null;
  "chunk": ChunkRecord | null;
  "embeddings": EmbeddingRecord[];
  "review_task": Record<string, unknown> | null;
};

export type KnowledgeUnitExportRequest = {
  "format"?: "markdown" | "json";
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "knowledge_unit_ids"?: string[];
  "include_chunks"?: boolean;
  "include_sources"?: boolean;
  "include_pending_review"?: boolean;
};

export type KnowledgeUnitOrganizationBatchUpdateRequest = {
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "knowledge_unit_ids": string[];
};

export type KnowledgeUnitRecord = {
  "id": string;
  "source_id": string;
  "chunk_id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "type": string;
  "content": string;
  "status": string;
  "user_verified": boolean;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "created_at": string;
  "updated_at": string;
};

export type MemoryDraftRecord = {
  "id": string;
  "project_id": string;
  "source_answer_id": string;
  "content": string;
  "memory_type": "preference" | "decision" | "style" | "conclusion" | "reusable_context";
  "status": string;
  "permission": string;
  "user_confirmed": boolean;
  "review_task_id": string | null;
  "created_at": string;
  "updated_at": string;
};

export type MemoryDraftRequest = {
  "source_answer_id": string;
  "content": string;
  "memory_type": "preference" | "decision" | "style" | "conclusion" | "reusable_context";
  "permission"?: string;
  "project_id"?: string;
};

export type OrganizationBatchUpdateResponse = {
  "target_type": string;
  "project_id": string;
  "requested_ids": string[];
  "updated_ids": string[];
  "updated_count": number;
  "folder_id": string | null;
  "tags": TagRecord[];
  "synced_knowledge_unit_ids": string[];
  "updated_at": string;
};

export type OrganizationUpdateRequest = {
  "folder_id"?: string | null;
  "tag_ids"?: string[];
};

export type OrganizationUpdateResponse = {
  "target_type": string;
  "target_id": string;
  "project_id": string;
  "folder_id": string | null;
  "tags": TagRecord[];
  "synced_knowledge_unit_ids": string[];
  "updated_at": string;
};

export type ParseTaskRecord = {
  "id": string;
  "file_id": string;
  "source_id": string | null;
  "job_id": string;
  "parser_key": string;
  "status": string;
  "capability_status": string;
  "fallback_reason": string | null;
  "error_code": string | null;
  "source": SourceRecord | null;
  "chunk_ids": string[];
  "warnings": ParseWarningRecord[];
  "created_at": string;
  "updated_at": string;
};

export type ParseWarningRecord = {
  "id": string;
  "parse_task_id": string;
  "warning_type": string;
  "severity": string;
  "message": string;
  "source_location": string | null;
  "created_at": string;
};

export type ProjectCreateRequest = {
  "name": string;
  "description"?: string | null;
  "parent_id"?: string | null;
  "kb_type"?: "project_kb" | "reference_kb" | "person_kb" | "timeline_kb" | "inspiration_kb" | "method_kb" | "custom";
};

export type ProjectExportRequest = {
  "project_id"?: string;
  "include_pending_review"?: boolean;
  "format"?: string;
};

export type ProjectRecord = {
  "id": string;
  "user_id": string;
  "parent_id": string | null;
  "name": string;
  "description": string | null;
  "kb_type": string;
  "status": string;
  "metadata": Record<string, unknown>;
  "created_at": string;
  "updated_at": string;
};

export type RetrievalPreviewRequest = {
  "query": string;
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
};

export type RetrievalPreviewResponse = {
  "retrieval_log_id": string;
  "evidence_pack_id": string;
  "query": string;
  "query_explanation": Record<string, unknown>;
  "evidence_pack": EvidencePackDetail;
  "evidence_item_ids": string[];
  "citation_labels": string[];
  "citation_trace_summary": string;
  "provider_status": string;
  "fallback_reason": string | null;
};

export type ReviewActionResponse = {
  "review_task_id": string;
  "target_id": string;
  "status": string;
};

export type ReviewTask = {
  "id": string;
  "target_type": string;
  "target_id": string;
  "status": string;
  "payload": Record<string, unknown>;
};

export type RuntimeResponse = {
  "runtime_state": string;
  "status_reason": string | null;
  "sidecar": Record<string, unknown>;
  "database": Record<string, unknown>;
  "worker": Record<string, unknown>;
  "vector": Record<string, unknown>;
};

export type SettingsPatchRequest = {
  "language": "zh-CN" | "en-US";
};

export type SettingsResponse = {
  "language": "zh-CN" | "en-US";
  "persistence": string;
  "updated_at": string | null;
};

export type SourceDetail = {
  "id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "source_type": string;
  "source_origin": string;
  "content_hash": string;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "chunk_count": number;
  "created_at": string;
  "chunks": ChunkRecord[];
};

export type SourceOrganizationBatchUpdateRequest = {
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "source_ids": string[];
};

export type SourceRecord = {
  "id": string;
  "project_id": string;
  "primary_folder_id"?: string | null;
  "title": string;
  "source_type": string;
  "source_origin": string;
  "content_hash": string;
  "metadata": Record<string, unknown>;
  "tags"?: TagRecord[];
  "chunk_count": number;
  "created_at": string;
};

export type SystemStatusResponse = {
  "app": Record<string, unknown>;
  "database": Record<string, unknown>;
  "provider": Record<string, unknown>;
  "vector": Record<string, unknown>;
};

export type TagCreateRequest = {
  "project_id"?: string;
  "name": string;
  "namespace"?: "folder" | "topic" | "status" | "use" | "discipline" | "system" | "custom";
  "tag_type"?: "folder_tag" | "topic_tag" | "discipline_tag" | "status_tag" | "use_tag" | "system_tag" | "custom_tag";
  "description"?: string | null;
};

export type TagRecord = {
  "id": string;
  "project_id": string;
  "user_id": string;
  "name": string;
  "namespace": string;
  "tag_type": string;
  "description": string | null;
  "created_by": string;
  "created_at": string;
  "updated_at": string;
};

export type TextImportRequest = {
  "title": string;
  "content": string;
  "project_id"?: string;
};

export type TextImportResponse = {
  "job_id": string;
  "source_id": string;
  "chunk_ids": string[];
  "candidate_knowledge_unit_ids": string[];
  "review_task_ids": string[];
};

export type TextToSqlPreviewRequest = {
  "query": string;
  "project_id"?: string;
  "folder_id"?: string | null;
  "tag_ids"?: string[];
  "limit"?: number;
};

export type TextToSqlPreviewResponse = {
  "retrieval_log_id": string;
  "template_id": string;
  "intent": string;
  "generated_sql": string;
  "parameters": Record<string, unknown>;
  "readonly": boolean;
  "safety_status": string;
  "columns": string[];
  "rows": Record<string, unknown>[];
  "row_count": number;
  "query_explanation": Record<string, unknown>;
  "provider_status": string;
  "fallback_reason": string | null;
};

export type UploadCreateRequest = {
  "filename": string;
  "size_bytes": number;
  "content_type"?: string | null;
  "sha256"?: string | null;
  "part_size"?: number | null;
  "project_id"?: string;
};

export type UploadPartResponse = {
  "upload_id": string;
  "part_no": number;
  "size_bytes": number;
  "sha256": string;
  "received_bytes": number;
  "status": string;
};

export type UploadPartSummary = {
  "part_no": number;
  "size_bytes": number;
  "sha256": string;
  "created_at": string;
};

export type UploadSnapshot = {
  "id": string;
  "project_id": string;
  "original_filename": string;
  "content_type": string | null;
  "expected_size": number;
  "part_size": number;
  "part_count": number;
  "expected_sha256": string | null;
  "received_bytes": number;
  "status": string;
  "file_id": string | null;
  "job_id": string | null;
  "recoverable": boolean;
  "error_code": string | null;
  "parts": UploadPartSummary[];
  "integrity_check": FileIntegrityCheck | null;
  "inspection": FileInspectionSummary | null;
  "created_at": string;
  "updated_at": string;
};

export type ValidationError = {
  "loc": string | number[];
  "msg": string;
  "type": string;
};

export type WorkspaceSummaryResponse = {
  "project_count": number;
  "folder_count": number;
  "tag_count": number;
  "upload_count": number;
  "file_count": number;
  "pending_file_count": number;
  "source_count": number;
  "chunk_count": number;
  "knowledge_unit_count": number;
  "pending_review_count": number;
  "evidence_pack_count": number;
};

export type ApiPath =
  | "/api/health"
  | "/api/system/runtime"
  | "/api/system/status"
  | "/api/system/diagnostics:export"
  | "/api/workspace/summary"
  | "/api/auth/status"
  | "/api/settings"
  | "/api/projects"
  | "/api/folders"
  | "/api/tags"
  | "/api/sources/{source_id}/organization"
  | "/api/sources/organization:batch"
  | "/api/knowledge-units/{knowledge_unit_id}/organization"
  | "/api/knowledge-units/organization:batch"
  | "/api/uploads"
  | "/api/uploads/{upload_id}/parts/{part_no}"
  | "/api/uploads/{upload_id}:complete"
  | "/api/uploads/{upload_id}"
  | "/api/files"
  | "/api/files/{file_id}"
  | "/api/files/{file_id}:verify"
  | "/api/files/{file_id}:parse"
  | "/api/parse-tasks/{parse_task_id}"
  | "/api/sources"
  | "/api/sources/{source_id}"
  | "/api/knowledge-units:extract"
  | "/api/knowledge-units"
  | "/api/knowledge-units/{knowledge_unit_id}"
  | "/api/exports/knowledge-units"
  | "/api/exports/project"
  | "/api/exports/history"
  | "/api/exports/history/{history_id}"
  | "/api/feedback"
  | "/api/feedback/summary"
  | "/api/feedback/export"
  | "/api/feedback/export-history"
  | "/api/feedback/export-history/{history_id}"
  | "/api/memory-drafts"
  | "/api/memory-drafts/{memory_id}"
  | "/api/text-to-sql/preview"
  | "/api/text-imports"
  | "/api/jobs/{job_id}"
  | "/api/jobs/{job_id}/events:stream"
  | "/api/review-tasks"
  | "/api/review-tasks/{task_id}:confirm"
  | "/api/review-tasks/{task_id}:ignore"
  | "/api/retrieval/evidence-only"
  | "/api/retrieval/preview"
  | "/api/evidence-packs/{evidence_pack_id}"
  | "/api/evidence-packs/{evidence_pack_id}/annotations"
  | "/api/evidence-packs/{evidence_pack_id}/annotations:batch"
  | "/api/citation-annotations/{annotation_id}"
  | "/api/evidence-packs/{evidence_pack_id}/compare"
;
